### ISSUE TITLE
 Given groups=1, weight of size [32, 1, 3, 3], expected input[6016, 3, 130, 130] to have 1 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by sAuDoisy** [clovaai/mxfont#14]
I, I just broke down, I don't know why I can not val the picture, the training result is so good.

**Comment by SanghyukChun** [comment]
First, please specify a detailed walkthrough for reproducing your error. We cannot solve your problem without understanding what the problem is.
Second, we presume that you pass 3 channel input (i.e., RGB images) rather than 1 channel input.
Add `img.convert('L')` for converting your RGB image to grey-scale (https://stackoverflow.com/questions/52307290/what-is-the-difference-between-images-in-p-and-l-mode-in-pil)

Please carefully follow the instruction in the document first, and if you still have a problem, please re-open the issue
https://github.com/clovaai/mxfont/blob/main/readme.md
