### ISSUE TITLE
How to fix the broken stroke in the result Image

### ISSUE THREAD

**Issue by ghost** [clovaai/mxfont#17]
For example. 
![截屏2022-12-16 09 15 05](https://user-images.githubusercontent.com/20164277/207999670-9eae2f6c-cb23-40de-9dd4-4a9e8c9c9afb.png)
should be 落

**Comment by SanghyukChun** [comment]
Please check my previous comment.
If you need really good font generation results, we suggest you apply many-shot methods (fine-tuning on the reference characters) such as [zi2zi](https://github.com/kaonashi-tyc/zi2zi)
https://github.com/clovaai/mxfont/issues/8#issuecomment-894605452

Because it is not the issue of the current implementation, but a potential improvement feature, I close the issue
