### ISSUE TITLE
Why are there significant differences between the images generated in training and those generated in test files

### ISSUE THREAD

**Issue by zhenzi0322** [clovaai/mxfont#24]

**Comment by zhenzi0322** [comment]
![image](https://github.com/clovaai/mxfont/assets/34839719/e405ec0b-2628-4a25-9709-53e71306b159)

**Comment by SanghyukChun** [comment]
It could be because our repository is not designed for commercial use or perfect font generation but for academic research in a controlled environment. Note that generative AI is still not perfect, and these types of artifacts can always happen.

I closed this issue because the quality of the generated image cannot be perfect. Please check other font generation repositories if you need.
