### ISSUE TITLE
Is the content and style classifier pre trained, or are they trained together with mxfont

### ISSUE THREAD

**Issue by jingmingtao** [clovaai/mxfont#28]
Is the content and style classifier pre trained, or are they trained together with mxfont

**Comment by SanghyukChun** [comment]
If you mean classifiers for the evaluation, they are separately trained with MX-Font.

**Comment by jingmingtao** [comment]
What I mean is that the classifier was trained in advance before mxfont training, how to start training the classifier, and I did not find any saved classification models during the training



---Original---
From: "Sanghyuk ***@***.***&gt;
Date: Wed, Nov 8, 2023 08:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [clovaai/mxfont] Is the content and style classifier pre trained,or are they trained together with mxfont (Issue #28)




 
If you mean classifiers for the evaluation, they are separately trained with MX-Font.

**Comment by SanghyukChun** [comment]
It doesn't matter when you start to train the classifiers. They are only used for evaluation, hence you can train them whatever and whenever you want. We did not include the font classifier training process in this code repository.

**Comment by jingmingtao** [comment]
The paper says'.We employ two feature classifiers, Cls s and Cls u to
supervise f s,i and f c,i , which serve as weak supervision for
f i . ', but no training code is provided. Do I not have this classifier



---Original---
From: "Sanghyuk ***@***.***&gt;
Date: Wed, Nov 8, 2023 09:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [clovaai/mxfont] Is the content and style classifier pre trained,or are they trained together with mxfont (Issue #28)




 
It doesn't matter when you start to train the classifiers. They are only used for evaluation, hence you can train them whatever and whenever you want. We did not include the font classifier training process in this code repository.

**Comment by SanghyukChun** [comment]
That is another one rather than the evaluation one. Please be more specific.
They are a part of the MX-Font module; hence they are initialized randomly and trained jointly with the generative modules.
You can check these codes:

The classifier architecture code
https://github.com/clovaai/mxfont/blob/fa3721e9a2fa9effee15431d86a4221cde4cabe4/models/aux_classifier.py#L12-L33

The training code for weak supervision
https://github.com/clovaai/mxfont/blob/fa3721e9a2fa9effee15431d86a4221cde4cabe4/trainer/fact_trainer.py#L277-L302

**Comment by jingmingtao** [comment]
Thanks very much!
