### ISSUE TITLE
abort program aborting

### ISSUE THREAD

**Issue by XuyangPan** [clovaai/mxfont#4]
Hello， the 313 fonts were collected and were made into dataset. During training mxfont model the program aborted.

Some losses were very abnormal. The log was recorded in the following.

![image](https://user-images.githubusercontent.com/39898699/120148055-36d81080-c21a-11eb-97f7-e9926e5fddd9.png)

**Comment by XuyangPan** [comment]
The bug record

![image](https://user-images.githubusercontent.com/39898699/120148191-68e97280-c21a-11eb-817f-6849864cc9e5.png)

**Comment by SanghyukChun** [comment]
This is not a bug but a typical unstable GAN training.
We have also often observed similar unstable training as well.

Although the loss is explored from `INDP_FACT`, we suspect that the unstable training is originated from "cross CE" which potentially increases the classifier weight values -- we couldn't test whether this is true due to the time limitation.
If you want to make your model more stable, then I suggest you remove the "cross CE" in the following lines:
- https://github.com/clovaai/mxfont/blob/main/trainer/fact_trainer.py#L250
- https://github.com/clovaai/mxfont/blob/main/trainer/fact_trainer.py#L265
It will slightly reduce your final performances but may make the training stable. But, please note that we also don't have exact clue why the unstable training happens.

(+ In practice, we select the "last model" under stable loss values)

**Comment by 8uos** [comment]
Hi, sorry for the inconvenience.
You can exclude the cross CE loss by setting the weight of cross CE loss to zero.
It can be set by giving --ac_cross_w argument when running `train.py` like this:

` python train.py cfgs/train.yaml --ac_cross_w 0.`

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
