### ISSUE TITLE
a json file  Includes all Chinese characters in the data folder

### ISSUE THREAD

**Issue by pengyaru** [clovaai/mxfont#7]
I want to ask if there is a json file，similar to chn_primals.json and chn_gen.json in the data folder，which Includes all Chinese characters？ can you send me such file？ @8uos @SanghyukChun

**Comment by 8uos** [comment]
Hi. 
You can obtain the full Chinese characters list using the unicode character table, defined in Table 12.2 of this [document](http://www.unicode.org/versions/Unicode5.0.0/ch12.pdf#G12159).

However, we did not use all the characters defined in the unicode character table because many of them are not decomposable using the pre-defined decomposition table (We used [this](https://commons.wikimedia.org/wiki/Commons:Chinese_characters_decomposition) to build our decomposition table.)
If you are curious about the characters used for the training, just get the keys of the `data/chn_decomposition.json` file!

Note that, we only used the decomposable characters for the training but **the model can generate non-decomposable characters** when the model is fully trained.
Thanks.

**Comment by pengyaru** [comment]
Thank you for your reply,  @8uos . And I have two more questions.
(1) what‘s the difference between self.gen and self.gen_ema in fact_trainer.py?
(2) If I want to use 100 (instead of 4)  target domain images as ref_imgs in the test in imagefolder_dataset.py while running eval.py, do I also use "ref_imgs = torch.stack([self.transform(Image.open(str(self.data_dir / font / f"{rc}"))) for rc in self.font_ref_chars[font]])"?  Or there are other better ways？
Hope your reply.  @8uos @SanghyukChun

**Comment by 8uos** [comment]
(1) Difference between `self.gen` and `self.gen_ema`.
`self.gen` and `self.gen_ema` have totally identical structures but their weights are updated differently. 
`self.gen` is directly updated by the optimizer during the training and `self.gen_ema` is updated using the exponential moving average (EMA).
If you are curious about how the `self.gen_ema` is updated, please refer this method([code](https://github.com/clovaai/mxfont/blob/6791eecb50ea66705da8befaf1db72582bdb18e3/trainer/base_trainer.py#L75)).

(2) Using more reference images.
Sorry for the inconvenience. I added an example file to generate a single reference style with many reference images. Please see [`inference.ipynb`](https://github.com/clovaai/mxfont/blob/main/inference.ipynb) file.

Thanks for the waiting.

**Comment by SanghyukChun** [comment]
Closing the issue, assuming the answer resolves the problem.
Please re-open the issue as necessary.
